input_path: D:/gracode/sr_data/pic/Set14/image_SRF_4/LR/img_002.png
model_path: D:/gracode/sr_models/Pic/ESRGAN/ESRGAN_PSNR_SRx4_DF2K_official-150ff491.pth
output_folder: D:/gracode/sr_results/gpt
selected_model: ESRGAN
