input_path: D:/gracode/sr_data/video/video_12f.mp4
model_path: D:/gracode/sr_models/Pic/ESRGAN/ESRGAN_SRx4_DF2KOST_official-ff704c30.pth
output_folder: D:/gracode/sr_results/22
selected_model: BasicVSR
